[package]
name = "sqlformater"
version = "1.0.11"
edition = "2024"

[dependencies]
mylog = "0.1.4"
rayon = "1.10.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.142"
sqlparser = "0.58.0"
